### ISSUE TITLE
En PS V 1.7.8.0 no deja validar en el final de compra.

### ISSUE THREAD

**Issue by Luifer-dnk** [BlindersGroup/classicblinders#10]
Al finalizar el proceso de compra con todas las opciones marcadas correctamente, no se activa el botón para finalizar la compra.

He probado y en el tpl "payment" del tema falta código que imagino que actualiza el estado para finalizar la compra.

Gracias miles por el tremendo tema, grandes.

**Comment by DevBlinders** [comment]
Solucionado en la versión 1.5.9 del theme, ya disponible para la descarga en la web y en la rama main
